# Generated by Django 5.1.15 on 2026-09-19 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300, verbose_name='Direccion')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, default='', max_length=100, verbose_name='Estado/Departamento')),
                ('postal_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Codigo postal')),
                ('country', models.CharField(default='Colombia', max_length=50, verbose_name='Pais')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='businesses.business', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Ubicacion',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
    ]
