# Generated by Django 5.2.17 on 2026-09-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesslocation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='businesslocation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='businesslocation',
            name='state',
        ),
        migrations.AddField(
            model_name='businesslocation',
            name='municipality',
            field=models.CharField(blank=True, default='', help_text='Ej: Santo Domingo, Santiago', max_length=100, verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='businesslocation',
            name='province',
            field=models.CharField(blank=True, default='', help_text='Ej: Distrito Nacional, Santiago', max_length=100, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='businesslocation',
            name='sector',
            field=models.CharField(blank=True, default='', help_text='Ej: Piantini, Naco, Zona Colonial', max_length=100, verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='businesslocation',
            name='street',
            field=models.CharField(default='', help_text='Ej: Av. Winston Churchill #12', max_length=200, verbose_name='Calle y número'),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='country',
            field=models.CharField(default='República Dominicana', max_length=50, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='postal_code',
            field=models.CharField(blank=True, default='', help_text='Ej: 10100', max_length=10, verbose_name='Código Postal'),
        ),
    ]
