# Generated by Django 5.2.17 on 2026-09-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_locations', '0003_migrate_location_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesslocation',
            name='district',
            field=models.CharField(blank=True, default='', help_text='Ej: Distrito Nacional', max_length=100, verbose_name='Distrito Municipal'),
        ),
    ]
