# Generated by Django 5.2.17 on 2026-10-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_locations', '0004_businesslocation_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesslocation',
            name='referencias',
            field=models.CharField(blank=True, default='', help_text='Ej: frente a la parada de bus, al lado de la farmacia. Sirve para llegar a pie; no sustituye las coordenadas.', max_length=300, verbose_name='Referencias'),
        ),
    ]
