# Generated by Django 5.1.15 on 2026-09-19 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('operational_status', '0001_initial'),
        ('publication_status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('short_description', models.CharField(blank=True, default='', max_length=300, verbose_name='Descripción corta')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='categories.category', verbose_name='Categoría')),
                ('operational_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='operational_status.operationalstatus', verbose_name='Estado operativo')),
                ('publication_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='businesses', to='publication_status.publicationstatus', verbose_name='Estado de publicación')),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
