# Generated by Django 5.2.17 on 2026-09-20 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_featured_tier'),
        ('categories', '0002_category_parent_alter_category_name_and_more'),
        ('publication_status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='featured_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin destacado'),
        ),
        migrations.AddField(
            model_name='business',
            name='featured_permanent',
            field=models.BooleanField(default=False, help_text='Si esta activo, el destacado no expira.', verbose_name='Destacado permanente'),
        ),
        migrations.AddField(
            model_name='business',
            name='featured_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio destacado'),
        ),
        migrations.AddField(
            model_name='business',
            name='featured_weeks',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1 semana'), (2, '2 semanas'), (3, '3 semanas'), (4, '4 semanas')], help_text='Duracion en semanas del destacado.', null=True, verbose_name='Semanas destacado'),
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='categories.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='business',
            name='featured_tier',
            field=models.CharField(blank=True, choices=[('large', 'Grande'), ('medium', 'Mediano'), ('small', 'Pequeno')], help_text='Grande = tarjeta grande, Mediano = tarjeta media, Pequeno = tarjeta pequena', max_length=10, null=True, verbose_name='Nivel de destacado'),
        ),
        migrations.AlterField(
            model_name='business',
            name='publication_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='businesses', to='publication_status.publicationstatus', verbose_name='Estado de publicacion'),
        ),
        migrations.AlterField(
            model_name='business',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Descripcion corta'),
        ),
    ]
