# Generated by Django 5.2.17 on 2026-09-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_business_featured_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='featured_tier',
            field=models.CharField(blank=True, choices=[('1', 'Nivel 1 - Principal'), ('2', 'Nivel 2 - Alto'), ('3', 'Nivel 3 - Medio'), ('4', 'Nivel 4 - Basico')], help_text='Nivel de relevancia del destacado (1=principal, 4=basico)', max_length=10, null=True, verbose_name='Nivel de destacado'),
        ),
    ]
