# Generated by Django 5.2.17 on 2026-09-29 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_alter_business_featured_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(choices=[('nombre', 'Nombre del negocio'), ('direccion', 'Direccion'), ('telefono', 'Telefono / WhatsApp'), ('categoria', 'Categoria'), ('descripcion', 'Descripcion'), ('estado', 'Estado (abierto/cerrado)'), ('horario', 'Horario'), ('otro', 'Otro')], max_length=20, verbose_name='Dato incorrecto')),
                ('mensaje', models.TextField(help_text='Texto que lee el admin.', verbose_name='Que esta mal / cual es el dato correcto')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisada', 'Revisada'), ('aplicada', 'Aplicada'), ('descartada', 'Descartada')], default='pendiente', max_length=12, verbose_name='Estado')),
                ('nota_admin', models.TextField(blank=True, default='', verbose_name='Nota interna del admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resuelta el')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='businesses.business', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Correccion',
                'verbose_name_plural': 'Correcciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
