# Generated by Django 5.2.17 on 2026-10-01 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_alter_business_slug_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='procedencia',
            field=models.CharField(choices=[('manual', 'Manual'), ('importado', 'Importado (automatico)'), ('levantado', 'Levantado por colaborador'), ('verificado', 'Verificado por humano')], default='manual', help_text='De donde salio la ficha. "importado" se anade solo, para senalar lo que nadie ha revisado todavia.', max_length=12, verbose_name='Procedencia'),
        ),
    ]
