# Generated by Django 5.2.17 on 2026-10-01 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_business_procedencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('token', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Token de firma')),
                ('municipio', models.CharField(blank=True, default='', help_text='Solo informativo: el municipio de cada envio lo declara el propio envio, no el token.', max_length=100, verbose_name='Municipio')),
                ('activo', models.BooleanField(default=True, help_text='Apagarlo bloquea a este colaborador sin tocar a los demas.', verbose_name='Activo')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('ultimo_envio', models.DateTimeField(blank=True, null=True, verbose_name='Ultimo envio')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('publicado', 'Publicado'), ('pendiente', 'Pendiente (falta el trio)'), ('rechazado', 'Rechazado en la puerta'), ('duplicado', 'Ya existia')], default='pendiente', max_length=12, verbose_name='Decision del sistema')),
                ('motivos', models.JSONField(blank=True, default=list, help_text='Por que se rechazo. Solo cuando estado es "rechazado".', verbose_name='Motivos')),
                ('faltan', models.JSONField(blank=True, default=list, help_text='Que le falta al negocio para cumplir el trio. Es lo que se le devuelve al colaborador para que lo complete.', verbose_name='Campos que faltan')),
                ('datos', models.JSONField(blank=True, default=dict, help_text='Copia literal de lo que llego, para auditar.', verbose_name='Datos recibidos')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('recibido_el', models.DateTimeField(auto_now_add=True, verbose_name='Recibido el')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios', to='businesses.colaborador', verbose_name='Colaborador')),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='businesses.business', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Envio',
                'verbose_name_plural': 'Envios',
                'ordering': ['-recibido_el'],
            },
        ),
    ]
