# Generated by Django 5.1.15 on 2026-09-19 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10, verbose_name='Día')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='Hora de apertura')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='Hora de cierre')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Cerrado este día')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='businesses.business', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['day'],
                'unique_together': {('business', 'day')},
            },
        ),
    ]
