# Generated by Django 5.2.17 on 2026-09-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_hours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesshours',
            name='is_holiday',
            field=models.BooleanField(default=False, help_text='Si se marca, el sistema mostrara "Cerrado (Fiesta)" este dia.', verbose_name='Dia de fiesta'),
        ),
    ]
