# Generated by Django 5.1.15 on 2026-09-19 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono')),
                ('whatsapp', models.CharField(blank=True, default='', help_text='Número con código de país, ej: +573001234567', max_length=20, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo')),
                ('website', models.URLField(blank=True, default='', verbose_name='Sitio web')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='businesses.business', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
    ]
