# Generated by Django 5.2.17 on 2026-09-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscontact',
            name='contact_person',
            field=models.TextField(blank=True, default='', help_text='Nombre del responsable o persona de contacto cuando el negocio no tiene teléfono/correo propio.', verbose_name='Contacto'),
        ),
    ]
