# Generated by Django 5.1.15 on 2026-09-19 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='businesses/images/', verbose_name='Imagen')),
                ('caption', models.CharField(blank=True, default='', max_length=200, verbose_name='Descripción')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Imagen principal')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='businesses.business', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imágenes',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
