# Generated by Django 5.2.17 on 2026-09-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_images', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessimage',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Imagen del negocio', 'verbose_name_plural': 'Imagenes del negocio'},
        ),
        migrations.RemoveField(
            model_name='businessimage',
            name='is_primary',
        ),
        migrations.AlterField(
            model_name='businessimage',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Pie de foto'),
        ),
        migrations.AlterField(
            model_name='businessimage',
            name='image',
            field=models.FileField(upload_to='business_images/%Y/%m/', verbose_name='Imagen'),
        ),
    ]
