# Generated by Django 5.2.17 on 2026-09-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_images', '0002_alter_businessimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessimage',
            name='image',
            field=models.ImageField(upload_to='business_images/%Y/%m/', verbose_name='Imagen'),
        ),
    ]
